# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3231777beef5e08c3678e434b1f701b84a948e5a3d9cf78442bbd3d1bb76cf992cdde15714125b552537889bc101b8d1d51453775423246bd9f827d7f538e3d

test:
  secret_key_base: 98d0326062308c1d6eb557c06dd68f1fd01fab81c6cf63569c9197e2e96e54504fbfdb26d6cde7fdaf11cd4909abb124927bb79c17aab4f32a25e037b0755f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
